/*
 * config.h
 *
 *  Created on: Nov 13, 2020
 *      Author: vasily
 */

#ifndef _CONFIG_H_
#define _CONFIG_H_

#include "drivers.h"

/** Частота шины HCLK (работы ядра процессора). */
#define HCLK_FREQ	120000000

#define CURRENT_MESSAGE_LEVEL 2

#define D85_ADDR					0x42 /*I2C0*/
#define D86_ADDR					0x44 /*I2C0*/
#define D87_ADDR					0x46 /*I2C0*/
#define D88_ADDR					0x42 /*I2C1*/


#define ON_BTN_PIN					LL_GPIO_PIN_15
#define ON_BTN_PORT					GPIOC

#define	PS_ON_BMC_PIN				LL_GPIO_PIN_13
#define PS_ON_BMC_PORT				GPIOD

#define	PWR_OK_BMC_PIN				LL_GPIO_PIN_14
#define PWR_OK_BMC_PORT				GPIOD

#define	PWRGD_VDDIO_CPU0_PIN		LL_GPIO_PIN_6
#define PWRGD_VDDIO_CPU0_PORT		GPIOA

#define	PWRGD_VDDIO_CPU1_PIN		LL_GPIO_PIN_8
#define PWRGD_VDDIO_CPU1_PORT		GPIOD

#define	CPU0_VDDQABC_PWRGD_PIN		LL_GPIO_PIN_7
#define CPU0_VDDQABC_PWRGD_PORT		GPIOE

#define	CPU0_VDDQDEF_PWRGD_PIN		LL_GPIO_PIN_4
#define CPU0_VDDQDEF_PWRGD_PORT		GPIOF

#define	PWRGD_VPP_CPU0_ABC_PIN		LL_GPIO_PIN_13
#define PWRGD_VPP_CPU0_ABC_PORT		GPIOE

#define	PWRGD_VPP_CPU0_DEF_PIN		LL_GPIO_PIN_9
#define PWRGD_VPP_CPU0_DEF_PORT		GPIOF

#define	PWRGD_VTT_CPU0_ABC_PIN		LL_GPIO_PIN_9
#define PWRGD_VTT_CPU0_ABC_PORT		GPIOE

#define	PWRGD_VTT_CPU0_DEF_PIN		LL_GPIO_PIN_5
#define PWRGD_VTT_CPU0_DEF_PORT		GPIOF

#define	CPU1_VDDQ_PWRGD_PIN			LL_GPIO_PIN_0
#define CPU1_VDDQ_PWRGD_PORT		GPIOC

#define	PWRGD_VPP_CPU1_PIN			LL_GPIO_PIN_7
#define PWRGD_VPP_CPU1_PORT			GPIOC

#define	PWRGD_VTT_CPU1_PIN			LL_GPIO_PIN_8
#define PWRGD_VTT_CPU1_PORT			GPIOC

#define	VDD_PCIE_VPH_CPU0_EN_PIN	LL_GPIO_PIN_12
#define VDD_PCIE_VPH_CPU0_EN_PORT	GPIOE

#define	PWRGD_VDD_PCIE_VPH_CPU0_PIN		LL_GPIO_PIN_15
#define PWRGD_VDD_PCIE_VPH_CPU0_PORT	GPIOG

#define	VDD_PCIE_VP_CPU0_EN_PIN			LL_GPIO_PIN_10
#define VDD_PCIE_VP_CPU0_EN_PORT		GPIOE

#define	PWRGD_VDD_PCIE_VP_CPU0_PIN		LL_GPIO_PIN_0
#define PWRGD_VDD_PCIE_VP_CPU0_PORT		GPIOA

#define	VDD_PCIE_VPH_CPU1_EN_PIN		LL_GPIO_PIN_6
#define VDD_PCIE_VPH_CPU1_EN_PORT		GPIOF

#define	PWRGD_VDD_PCIE_VPH_CPU1_PIN		LL_GPIO_PIN_1
#define PWRGD_VDD_PCIE_VPH_CPU1_PORT	GPIOD

#define	VDD_PCIE_VP_CPU1_EN_PIN			LL_GPIO_PIN_3
#define VDD_PCIE_VP_CPU1_EN_PORT		GPIOF

#define	PWRGD_VDD_PCIE_VP_CPU1_PIN		LL_GPIO_PIN_0
#define PWRGD_VDD_PCIE_VP_CPU1_PORT		GPIOF

#define	CPU0_VDD_PWRGD_PIN				LL_GPIO_PIN_8
#define CPU0_VDD_PWRGD_PORT				GPIOA

#define	CPU1_VDD_PWRGD_PIN				LL_GPIO_PIN_5
#define CPU1_VDD_PWRGD_PORT				GPIOD

//VDDIO_CPU1_EN_PIN				D85.IO0			O
//VDDIO_CPU0_EN					D85.IO0			O
//CPU0_VDDQABC_EN				D85.IO7			O
//CPU0_VDDQDEF_EN				D85.IO4			O
//VPP_CPU0_ABC_EN				D85.IO5			O
//VTT_CPU0_ABC_EN				D85.IO6			O
//VPP_CPU0_DEF_EN				D85.IO2			O
//VTT_CPU0_DEF_EN				D85.IO3			O
//CPU1_VDDQ_EN					D88.IO7			O
//VPP_CPU1_EN					D88.IO5			O
//VTT_CPU1_EN					D88.IO6			O
//CPU0_VDD_EN					D85.IO1			O
//CPU1_VDD_EN					D88.IO1			O

#endif /* _CONFIG_H_ */
